### ISSUE TITLE
ClientSocket.cs    using Steamworks.Data;  Error!

### ISSUE THREAD

**Issue by IndiaGameMaker** [TiToMoskito/FishyFacepunch#2]
![image](https://user-images.githubusercontent.com/1924146/161590242-89de2cbb-7b3a-430f-ad48-82e51dfbe065.png)
Is it the version that is the problem?
My fishNet is 1.4.3

**Comment by TiToMoskito** [comment]
Steamworks? Are you using the Steamworks implementation from Facepunch like in the Readme described?
